### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by ivancevich** [drone-plugins/drone-coverage#3] opened 2016-01-22 20:04 UTC
Hello,

First of all I'd like to thank you for all the great job done on Drone. It's awesome!

I've installed drone.io in a AWS Elastic Beanstalk instance and successfully configured it to run my tests every time I push to Github. Now I'm trying to add code coverage to the pipe. But I'm getting this error: `Cannot authenticate. Unable to authenticate user . Not registered.`
Looking through the code, I've noticed you have another service called aircover.co so I tried to login with Github. But it gives me an error saying that the registration is closed.

How can I do? Should I use another service for code coverage?

Thanks in advance!

**Comment by iascan** [comment] 2016-01-26 21:27
I can second this error, running drone 0.4 locally integrated with bitbucket.

**Comment by bradrydzewski** [comment] 2016-02-03 23:15
Hey there, this plugin is solely for publishing coverage reports to [aircover.co](https://aircover.co), and is not a generic coverage reporting plugin. The [aircover](https://aircover.co) service is still in private beta, but can be installed on your own servers https://aircover.co/docs/install/

> How can I do? Should I use another service for code coverage?

You can definitely integrate with other coverage services, but not using this plugin since it focuses solely on aircover. Someone would need to create a new plugin for coveralls or codecov.

> I can second this error, running drone 0.4 locally integrated with bitbucket.

Aircover does not support Bitbucket at this time, just GitHub and GitHub enterprise.

I'm going to close this because this is expected behavior. If you install your own aircover instance you will be able to use with this plugin. Please note that this plugin is still not officially released nor documented, so if you choose to use it and install aircover you should be willing to dig into the code and debug errors.

**Closed as completed** 2016-02-03 23:22 UTC

**Comment by ivancevich** [comment] 2016-02-04 04:06
Thanks for the in-depth explanation @bradrydzewski. Will try to install aircover on my own server.
